In [ ]:
# numpy
# numerical python의 약자 
# 고성능 수치 계산을 위한 라이브러리 
# 벡터나 행렬 연산에 편리한 기능 제공 
# 모든 원소는 같은 자료형만 가능

In [29]:
# arange 함수 : 데이터를 쭉 ~ 나열하는 함수 
import numpy as np
a = np.arange( 15 )
print(a) 
a = a.reshape(3,5, order='F')  # C : 행부터 할당, F : 열부터 할당
print(a)
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim) #몇차원 데이터냐
print(a.size) #데이터 개수 
# print(dir(np))



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
<class 'numpy.ndarray'>
(3, 5)
int64
2
15


In [31]:
print(a)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [87]:
b = [-1, 2, 5, -3, 0, 7, -9, 7, -4, -7] #list (데이터 중복 가능)
print(type(b))
b = np.array(b)
print(type(b))

t = ( 10, 20, 30, 40, 50) #tuple
print(type(t))
t = np.array(t)
print(type(t))

s = {10, 20, 30, 40, 50} #set (데이터 중복 불가)
print(type(s))
s = np.array(s)
print(type(s)) #기존에 있던 자료형도 numpy로 호환이 된다

<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'set'>
<class 'numpy.ndarray'>


In [105]:
print (b.shape)
print (b.ndim)
print (b.dtype)
print( b)

print (np.abs(b)) # 절대값 함수 
# print (np.sqrt(b)) # nan : 음수라 결과를 못 냄
print (np.square(b)) #제곱
print (np.isnan(b)) # nan 여부 
print (np.sum(b)) # 합계 구하는 함수 
print (np.mean(b)) # 평균 구하는 함수
print (np.max(b)) # 최대값 
print (np.min(b)) # 최소값 
print (np.argmax(b)) # 최대값의 위치값(인덱스)를 알려주는 함수 
print (np.argmin(b)) # 최솟값의 위치값
print (np.sort(b)) # 정렬 오름차순 
print (np.sort(b)[::-1]) # 정렬 내림차순 [시작 : 끝 : 간격] / -1 : 거꾸로

(10,)
1
int64
[-1  2  5 -3  0  7 -9  7 -4 -7]
[1 2 5 3 0 7 9 7 4 7]
[ 1  4 25  9  0 49 81 49 16 49]
[False False False False False False False False False False]
-3
-0.3
7
-9
5
6
[-9 -7 -4 -3 -1  0  2  5  7  7]
[ 7  7  5  2  0 -1 -3 -4 -7 -9]


In [29]:
import numpy as np
c = [ [ 1, 2, 3 ], [4, 5, 6] ]
print(type(c))
print(c) #리스트는 출력할 떄 콤마로 출력됨
c = np.array(c) #리스트에서 넘파이로 변경
print(type(c))
print(c) #넘파이는 줄바꿈 처리되어 출력됨

print(np.sum(c))
print(np.sum(c, axis=0))
print(np.sum(c, axis=1))
print(np.mean(c))
print(np.mean(c, axis=0))
print(np.mean(c, axis=1))
print(np.median(c))
print(np.median(c,axis=0))

<class 'list'>
[[1, 2, 3], [4, 5, 6]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
3.5
[2.5 3.5 4.5]
[2. 5.]
3.5
[2.5 3.5 4.5]


In [61]:
#element wise 
d = [10, 20, 30, 40, 50]
# print(d+2) #error
d = np.array(d)
print(d+2)

e = np.array([1,2,3,4,5])
print(d+e)

e = np.array ([1,2,3,4,5])
print (d+e)
print(d**2)
print(d*np.sin(d))
print(d>35)

print(np.add(d, e))
print(np.subtract(d, e))
print(np.multiply(d, e))
print(np.divide(d, e))

[12 22 32 42 52]
[11 22 33 44 55]
[11 22 33 44 55]
[ 100  400  900 1600 2500]
[ -5.44021111  18.25890501 -29.64094872  29.80452642 -13.11874269]
[False False False  True  True]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [71]:
f = np.array([[0, 1], [1, 1]])
g = np.array([[2, 0], [3, 4]])
print(f*g) #단순곱셈
print(f@g) #행렬곱
print (np.dot(f,g)) #행렬곱

[[0 0]
 [3 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]


In [99]:
h = np.zeros(10) #0이 10개가 들어있는 방을 만들어줘
print(h)
i = np.zeros ((5, 5))
print(i)
j = np.ones(10)
print(j)

k = np.random.random(10)*100
k = [int(i) for i in k] 
print(type(k))
print(k)

print(np.random.randint(10,20))
print(np.random.rand(5,2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'list'>
[0, 84, 4, 19, 23, 45, 43, 58, 3, 61]
15
[[0.97580577 0.18080289]
 [0.9102321  0.26107564]
 [0.70734335 0.3124225 ]
 [0.0213149  0.01961505]
 [0.78168673 0.80713449]]


In [115]:
#슬라이싱
m = [i for i in range(10,20)]
print(m[0:5])  #[시작 : 끝-1 : 간격]
print(m[0:5:2])
print(m[:])
print(m[5:])
print(m[:-1])
print(m[::-1]) #거꾸로 출력

#ndarray


[10, 11, 12, 13, 14]
[10, 12, 14]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[15, 16, 17, 18, 19]
[10, 11, 12, 13, 14, 15, 16, 17, 18]


In [135]:
r = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]
print(r[2][2])
print(r[:][:])
print(r[2][:])
print(r[1][:2])

s =  np.arange(1,16).reshape(3,5)
print(s)
print(s[2][2])
print(s[:][:])
print(s[2][:])
print(s[:2][:1])

print(s[:2, :2])
print(s[:, :])

13
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[11, 12, 13, 14, 15]
[6, 7]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
13
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
[[1 2 3 4 5]]
[[1 2]
 [6 7]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
